# Generated by Django 6.0 on 2025-12-05 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlogView',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(db_index=True, default='XX', max_length=2)),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=40, null=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='app.blog')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_views', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['author', 'published_at'], name='app_blog_author__65bb91_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['published_at'], name='app_blog_publish_6ed28d_idx'),
        ),
        migrations.AddIndex(
            model_name='blogview',
            index=models.Index(fields=['viewed_at', 'country'], name='app_blogvie_viewed__6ee570_idx'),
        ),
        migrations.AddIndex(
            model_name='blogview',
            index=models.Index(fields=['viewed_at', 'user'], name='app_blogvie_viewed__0aef76_idx'),
        ),
        migrations.AddIndex(
            model_name='blogview',
            index=models.Index(fields=['country', 'viewed_at'], name='app_blogvie_country_288c68_idx'),
        ),
        migrations.AddIndex(
            model_name='blogview',
            index=models.Index(fields=['user', 'viewed_at'], name='app_blogvie_user_id_bf98e5_idx'),
        ),
        migrations.AddIndex(
            model_name='blogview',
            index=models.Index(fields=['blog', 'viewed_at'], name='app_blogvie_blog_id_2dc43e_idx'),
        ),
        migrations.AddIndex(
            model_name='blogview',
            index=models.Index(fields=['viewed_at'], name='app_blogvie_viewed__0877a1_idx'),
        ),
    ]
